spring:
  profiles:
    active: ${EXECUTION_MODE:development}
  application:
    name: absences-backoffice
    description: "Absences Back Office"
    version: "0.0.1"
  flyway:
    enabled: true

server:
  port: ${DOCKER_INTERNAL_PORT:8080}

logging:
  level:
    root: INFO
    com.hftamayo.java.absencesbobe: DEBUG

version:
  api:
    current: v1
    supported: [v1, v2]
    legacy-support: true
    headers:
      enabled: true
      version-header: X-API-Version
      build-header: X-Build-Version

pagination:
  default-page-size: 5
  max-page-size: 100
  method: ${PAGINATION_METHOD:offset}

# Default rate limiting configuration
rate:
  limiter:
    default:
      capacity: 100
      refill-rate: 10
      refill-duration: PT1M

frontend:
  origins: ${FRONTEND_ORIGINS:http://localhost:5173}

# Common test user configuration
test:
  user:
    email: test@example.com
    password: ${TEST_USER_PASSWORD:123}

app:
  environment: ${EXECUTION_MODE:development}
