spring:
  config:
    activate:
      on-profile: test

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate

  test:
    database:
      replace: none

logging:
  level:
    root: WARN
    org.hibernate: WARN

rate:
  limiter:
    default:
      capacity: 10000
      refill-rate: 1000
      refill-duration: PT1S
  roles:
    ADMIN:
      capacity: 10000
      refill-rate: 1000
      refill-duration: PT1S
    SUPERVISOR:
      capacity: 10000
      refill-rate: 1000
      refill-duration: PT1S
    USER:
      capacity: 10000
      refill-rate: 1000
      refill-duration: PT1S

seed:
  development: false
  production: false

test:
  user:
    name: ${TEST_USER_NAME:test_user}
    password: ${TEST_USER_PASSWORD:test_password}
  db:
    name: ${TEST_DB_NAME:test_db}

app:
  environment: test