spring:
  config:
    activate:
      on-profile: staging

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:pgdevelopment}:${POSTGRES_PORT:5432}/${POSTGRES_DB:absencesbo}
    username: ${POSTGRES_USER:app}
    password: ${POSTGRES_PASSWORD:change_me}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 30000
      initialization-fail-timeout: 0
      idle-timeout: 600000
      max-lifetime: 1800000
      validation-timeout: 5000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when-authorized

logging:
  level:
    root: INFO
    com.hftamayo.java.absencesbobe: INFO
    com.zaxxer.hikari: WARN
    org.hibernate: WARN
    # If you want request/response details, consider enabling your package to DEBUG:
    # com.yourcompany.yourservice: DEBUG

rate:
  limiter:
    default:
      capacity: 100
      refill-rate: 10
      refill-duration: PT1M

  roles:
    ADMIN:
      capacity: 520
      refill-rate: 20
      refill-duration: PT1M
    SUPERVISOR:
      capacity: 200
      refill-rate: 20
      refill-duration: PT1M
    USER:
      capacity: 100
      refill-rate: 10
      refill-duration: PT1M